export const FETCH_RENTALS = 'FETCH_RENTALS';
export const RECIEVE_RENTALS = 'RECIEVE_RENTALS';
export const RECIEVE_SELECTED_RENTAL = 'RECIEVE_SELECTED_RENTAL';
export const REQUEST_SELECTED_RENTAL = 'REQUEST_SELECTED_RENTAL';
