export const FETCH_RENTALS = 'FETCH_RENTALS';
export const RECIEVE_RENTALS = 'RECIEVE_RENTALS';
export const RECIEVE_SELECTED_RENTAL = 'RECIEVE_SELECTED_RENTAL';
export const REQUEST_SELECTED_RENTAL = 'REQUEST_SELECTED_RENTAL';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
